[module]
message = "Module 01: Variables & Primitive Types"

[[exercises]]
name = "variables1"
path = "variables1/exercise.rs"
mode = "test"

[[exercises]]
name = "variables2"
path = "variables2/exercise.rs"
mode = "test"

[[exercises]]
name = "variables3"
path = "variables3/exercise.rs"
mode = "test"

[[exercises]]
name = "variables4"
path = "variables4/exercise.rs"
mode = "test"

[[exercises]]
name = "variables5"
path = "variables5/exercise.rs"
mode = "test"

[[exercises]]
name = "constants1"
path = "constants1/exercise.rs"
mode = "test"

[[exercises]]
name = "constants2"
path = "constants2/exercise.rs"
mode = "test"

[[exercises]]
name = "integers1"
path = "integers1/exercise.rs"
mode = "test"

[[exercises]]
name = "integers2"
path = "integers2/exercise.rs"
mode = "test"

[[exercises]]
name = "integers3"
path = "integers3/exercise.rs"
mode = "test"

[[exercises]]
name = "floats1"
path = "floats1/exercise.rs"
mode = "test"

[[exercises]]
name = "floats2"
path = "floats2/exercise.rs"
mode = "test"

[[exercises]]
name = "booleans1"
path = "booleans1/exercise.rs"
mode = "test"

[[exercises]]
name = "booleans2"
path = "booleans2/exercise.rs"
mode = "test"

[[exercises]]
name = "chars1"
path = "chars1/exercise.rs"
mode = "test"

[[exercises]]
name = "chars2"
path = "chars2/exercise.rs"
mode = "test"

[[exercises]]
name = "tuples1"
path = "tuples1/exercise.rs"
mode = "test"

[[exercises]]
name = "tuples2"
path = "tuples2/exercise.rs"
mode = "test"

[[exercises]]
name = "tuples3"
path = "tuples3/exercise.rs"
mode = "test"

[[exercises]]
name = "arrays1"
path = "arrays1/exercise.rs"
mode = "test"

[[exercises]]
name = "arrays2"
path = "arrays2/exercise.rs"
mode = "test"

[[exercises]]
name = "arrays3"
path = "arrays3/exercise.rs"
mode = "test"

[[exercises]]
name = "casting1"
path = "casting1/exercise.rs"
mode = "test"

[[exercises]]
name = "casting2"
path = "casting2/exercise.rs"
mode = "test"

[[exercises]]
name = "primitive_types_quiz"
path = "primitive_types_quiz/exercise.rs"
mode = "test"
