[module]
message = "M01: Variables & Primitive Types"

[exercises]
variables1 = "Variable Assignment"
variables2 = "Mutable Variables"
variables3 = "Shadowing Basics"
variables4 = "Type Inference"
variables5 = "Scope and Shadowing"
constants1 = "Constants Basics"
constants2 = "Constants vs Variables"
integers1 = "Integer Types"
integers2 = "Signed vs Unsigned"
integers3 = "Number Literals"
floats1 = "Floating Point"
floats2 = "Float Precision"
booleans1 = "Boolean Logic"
booleans2 = "Conditional Booleans"
chars1 = "Character Type"
chars2 = "Unicode Characters"
tuples1 = "Tuple Basics"
tuples2 = "Destructuring Tuples"
tuples3 = "Tuples as Return Values"
arrays1 = "Array Basics"
arrays2 = "Array Indexing"
arrays3 = "Array Initialization"
casting1 = "Type Casting Basics"
casting2 = "Integer Casting"
primitive_types_quiz = "Quiz: Primitives"
